language: ruby
rvm:
  - "2.0.0"
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database hpi_hiwi_portal_test;' -U postgres
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
