language: ruby
rvm:
- 2.5.1
sudo: false
before_script:
- cp config/database.travis.yml config/database.yml
- psql -c 'create database hpi_hiwi_portal_test;' -U postgres
git:
  submodules: false
cache: bundler
