mailToAdministration:	
  name: Mail Adress for administration   # sets the edit label
  default: "connect@hpi.uni-potsdam.de"  # sets the default value
  type: email                            # uses input type="email"
